---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo

  tasks:
    - name: packages
      include_tasks: packages.yaml

  tasks:
    - name: keepass2
      include_tasks: keepass2/index.yaml

  # tasks:
  #   - name: mullvad
  #     include_tasks: mullvad/index.yaml
