---
- name: Nomike's Unbuntu Desktop InSTaller
  hosts: localhost
  connection: local
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Include node roles
      ansible.builtin.include_tasks: "roles/{{ ansible_facts.nodename }}.yaml"
    # - name: mullvad
    #   ansible.builtin.include_tasks: mullvad/index.yaml
