---
- name: Nomike's Unbuntu Desktop InSTaller
  hosts: localhost
  connection: local
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Packages
      ansible.builtin.include_tasks: packages.yaml

    - name: Keepass2
      ansible.builtin.include_tasks: keepass2/index.yaml

    - name: Vlc
      ansible.builtin.include_tasks: vlc.yaml

    - name: Deconz
      ansible.builtin.include_tasks: deconz.yaml
    # - name: mullvad
    #   ansible.builtin.include_tasks: mullvad/index.yaml
