---
- hosts: localhost
  connection: local
  become: true
  become_method: sudo

  tasks:
    - name: Packages
      ansible.core.include_tasks: packages.yaml

    - name: Keepass2
      ansible.core.include_tasks: keepass2/index.yaml

    - name: Vlc
      ansible.core.include_tasks: vlc.yaml

    # - name: mullvad
    #   include_tasks: mullvad/index.yaml
