---
- name: "Scrooge: Basic desktop workstation"
  ansible.builtin.include_tasks: profiles/basic_desktop_workstation.yaml

- name: "Scrooge: Developer workstation"
  ansible.builtin.include_tasks: profiles/developer_workstation.yaml

- name: "Scrooge: LineageOS build platform"
  ansible.builtin.include_tasks: profiles/lineageos_build_platform.yaml

- name: "Scrooge: 3D print workstation"
  ansible.builtin.include_tasks: profiles/3d_print_workstation.yaml

