---
- name: "howdy: PPA"
  ansible.builtin.apt_repository:
    repo: "ppa:ubuntuhandbook1/howdy"
    state: present
    update_cache: true

- name: "howdy: Install howdy"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - howdy
