---
- name: "Github client: Install GPG key for githubcli apt repo"
  ansible.builtin.apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present

- name: "Github client: Install githubcli apt repository"
  ansible.builtin.apt_repository:
    repo: deb https://cli.github.com/packages stable main
    state: present

- name: "Github client: Apt update"
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: "Github client: install apt packages"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gh
