---
- name: "Basic tools: Install element.io GPG key"
  ansible.builtin.apt_key:
    url: https://packages.element.io/debian/element-io-archive-keyring.gpg
    state: present

- name: "Basic tools: Install element.io apt repository"
  ansible.builtin.apt_repository:
    repo: deb https://packages.element.io/debian default main
    state: present

- name: "Basic tools: Apt update"
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: "Basic tools: install apt packages"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ansible
      - ansible-lint
      - apt-transport-https
      - audacity
      - build-essential
      - cabextract
      - clang-format
      - cmake
      - curl
      - daemonize
      - dconf-editor
      - diffstat
      - diffutils
      - dos2unix
      - dosfstools
      - dotnet-sdk-6.0
      - dotnet-sdk-7.0
      - easy-rsa
      - element-desktop
      - feh
      - finger
      - flatpak
      - fonts-liberation
      - fonts-powerline
      - gdb
      - gddrescue
      - gimp
      - git
      - gitk
      - gnome-browser-connector
      - gnome-shell-extension-manager
      - gnome-tweaks
      - gnome-weather
      - google-android-platform-tools-installer
      - gparted
      - graphicsmagick-imagemagick-compat
      - guake
      - hexchat
      - htop
      - inkscape
      - ipython3
      - jq
      - jupp
      - keepass2
      - landscape-common
      - libfuse2
      - libreoffice-java-common
      - mc
      - mono-complete
      - mplayer
      - mtools
      - ncdu
      - net-tools
      - nmap
      - npm
      - openjdk-11-jdk
      - openjdk-11-jre
      - openjdk-17-jdk
      - openjdk-17-jre
      - openscad
      - openshot-qt
      - openssh-server
      - p7zip-full
      - pipx
      - playonlinux
      - plocate
      - pwgen
      - python3-autopep8
      - python3-docopt
      - python3-pip
      - python3-venv
      - python3-virtualenv
      - qdirstat
      - rpi-imager
      - sl
      - smartmontools
      - socat
      - solaar
      - sox
      - ssh-askpass-gnome
      - syncthing
      - tcpdump
      - thefuck
      - tig
      - ttf-mscorefonts-installer
      - unzip
      - virt-manager
      - vlc
      - vorta
      - wget
      - wireshark
      - whois
      - xclip
      - yamllint
      - yt-dlp
      - zsh
      - zsh-antigen