---
- name: "lineageos_build_platform: Install apt packages"
  ansible.builtin.apt:
    name:
      - bc
      - bison
      - build-essential
      - ccache
      - curl
      - flex
      - g++-multilib
      - gcc-multilib
      - git
      - git-lfs
      - gnupg
      - gperf
      - imagemagick
      - lib32readline-dev
      - lib32z1-dev
      - libelf-dev
      - liblz4-tool
      - libsdl1.2-dev
      - libssl-dev
      - libxml2
      - libxml2-utils
      - lzop
      - pngcrush
      - rsync
      - schedtool
      - squashfs-tools
      - xsltproc
      - zip
      - zlib1g-dev
    state: present

