- name: "Keepass2: install apt packages"
  ansible.builtin.apt:
    name: keepass2
    state: present

- name: "Keepass2: plugins: KeeOtp2"
  ansible.builtin.copy:
    dest: /usr/lib/keepass2/Plugins/KeeOtp2.plgx
    src: KeeOtp2.plgx
    mode: "0755"

- name: "Keepass2: plugins: KeePassRPC"
  ansible.builtin.copy:
    dest: /usr/lib/keepass2/Plugins/KeePassRPC.plgx
    src: KeePassRPC.plgx
    mode: "0755"
